package infrastructure;

import io.grpc.Channel;
import io.grpc.ManagedChannel;
import io.grpc.stub.StreamObserver;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import mapreduce.pb.Pair;
import mapreduce.pb.ShuffleReply;
import mapreduce.pb.ShuffleRequest;
import mapreduce.pb.WorkerGrpc;

/**
 * Step 3 of the pipeline, supplied. {@code mapreduce.Worker} extends this class,
 * so every Worker machine gets one of these and its task handlers sit on top
 * of it.
 *
 * <p>Why a superclass rather than a second service: the intermediate pairs have
 * to be reachable both from the handler that produced them and from the peer
 * that asks for them, and a simulated node constructs one handler per
 * {@code runs:} entry with a no-argument constructor. There is no seam through
 * which a second object could be handed the same store.
 *
 * <h4>Types</h4>
 *
 * <pre>
 *   k1 = map task index t       v1 = piece t of the input, generated by Corpus
 *   k2 = a word (String)        v2 = a count (Long; int64 in Pair)
 *
 *   map         : (t, piece)              -> list(word, 1)
 *   partition   : (word, R)               -> p in [0, R)       reduceTaskFor
 *   combine     : (word, list(count))     -> count             a sum, in store
 *   reduce      : (word, list(count))     -> count             a sum, yours, in mapreduce.Worker
 *
 *   map task    : (t, piece)                          -> R groups of (word, count), kept here
 *   reduce task : (p, group p of map tasks 0..M-1)    -> list(word, count), sorted by word
 * </pre>
 *
 * <p>These are the {@code mapTask} and {@code reduceTask} of Task 2's
 * {@code engine.Pipeline}, spread over machines.
 *
 * <h4>What was decided here, and why</h4>
 *
 * <ul>
 *   <li><b>The pairs are pulled, during the Reduce phase.</b> A pushed pair has
 *       to be addressed, and at map time there is no address: the Master does
 *       not pick the machine for reduce task p until the Reduce phase. A push
 *       would go to every machine and be discarded by all but one.
 *   <li><b>One map task's group for one reduce task is one message.</b> Per pair
 *       is M x R x keys calls; a whole map task's output moves R times the bytes
 *       the caller asked for.
 *   <li><b>The machine that counted partitions.</b> Every Worker applies the
 *       same rule to the same R, which is the only reason the groups fit
 *       together at the other end.
 *   <li><b>The counting happens before anything travels.</b> That is the
 *       combiner: {@code the} crosses the wire once with a number rather than
 *       once per occurrence. It is sound because summing counts in two passes
 *       gives the same answer as summing them in one, which is not true of every
 *       reduce function.
 * </ul>
 *
 * @see mapreduce.Worker
 */
public abstract class Shuffle extends WorkerGrpc.WorkerImplBase {

    /**
     * How long a shuffle read may wait. Longer than {@code Master.PING_MS},
     * shorter than {@code Master.TASK_MS}: the read happens inside a reduce
     * task, so it has to fail early enough for the reduce task to fail before
     * its own deadline and be handed to somebody else.
     */
    protected static final int FETCH_MS = 10_000;

    /**
     * map task -> reduce task -> key -> count.
     *
     * <p>Concurrent because this machine is touched from several places at once:
     * it answers {@link #fetch} for its peers while running a reduce task of its
     * own, and can be given a re-executed map task while both are in flight. A
     * plain {@code HashMap} corrupts under that, and it shows up as a total that
     * is slightly wrong rather than as a crash.
     */
    private final Map<Integer, Map<Integer, Map<String, Long>>> intermediate = new ConcurrentHashMap<>();

    /** One channel per peer, reused. Opening one per read would dominate the cost. */
    private final Map<String, ManagedChannel> channels = new ConcurrentHashMap<>();

    /**
     * Where a key belongs. The rule has to give the same answer on every machine
     * and at every moment, or a word is reduced in two places, the Master sums
     * both replies, and the output looks right.
     *
     * <p>{@code Math.floorMod} rather than {@code %}: {@code hashCode()} is
     * negative for about half of all strings and {@code %} keeps the sign. Those
     * pairs would be filed under a group index no reduce task asks for and would
     * disappear without an error.
     */
    public static int reduceTaskFor(String key, int reduceTasks) {
        return Math.floorMod(key.hashCode(), reduceTasks);
    }

    /**
     * Counts one piece, splits the counts into R groups, and keeps them on this
     * machine. Replaces anything this machine already held for that map task, so
     * a re-executed map task overwrites its earlier output; merging would double
     * every count and still produce a plausible answer.
     *
     * @return words read, counted before the combiner. Nothing here needs it;
     *         it is the number that shows what counting before transmission
     *         saves, if you decide the reply should carry it.
     */
    public final long store(int task, String piece, int reduceTasks) {
        if (reduceTasks < 1) {
            throw new IllegalArgumentException("reduce_tasks must be at least 1, was " + reduceTasks);
        }

        // ADOPTION EDIT. Add `dissaly.api.Dissaly.current().units(read);`
        // at the end of this method, after the loop. Until it is there, every
        // map task costs its scenario's `fixed` value whatever the size of its
        // piece, and the M comparison shows only the round count moving.
        // TRANSFORMATION.md has the line.

        // map: every word of the piece is a (word, 1).
        // partition: reduceTaskFor picks the group the word goes to.
        // combine: merge adds the 1 to that word's count within its group, so
        // the (word, 1) pairs are never held one by one.
        var groups = new HashMap<Integer, Map<String, Long>>();
        long read = 0;
        for (String word : piece.toLowerCase(Locale.ROOT).split("[^\\p{L}\\p{N}]+")) {
            if (word.isEmpty()) continue;
            read++;
            groups.computeIfAbsent(reduceTaskFor(word, reduceTasks), g -> new HashMap<>())
                  .merge(word, 1L, Long::sum);
        }

        intermediate.put(task, groups);
        return read;
    }

    /**
     * This machine's group {@code partition} out of map task {@code task}.
     *
     * @return the counts, an empty map when the machine holds that map task but
     *         produced nothing for that group, or {@code null} when it does not
     *         hold that map task at all
     */
    public final Map<String, Long> group(int task, int partition) {
        var forTask = intermediate.get(task);
        return forTask == null ? null : forTask.getOrDefault(partition, Map.of());
    }

    /**
     * Hands one group to whoever is running that reduce task.
     *
     * <p>It answers {@code found = false} instead of failing when this machine
     * does not hold the map task: it is alive and answering, it simply is not
     * the holder. Failing would be indistinguishable from the machine being
     * gone, and the caller has to tell those apart.
     */
    @Override public final void fetch(ShuffleRequest r, StreamObserver<ShuffleReply> out) {
        Map<String, Long> group = group(r.getTask(), r.getPartition());
        var reply = ShuffleReply.newBuilder().setFrom("worker").setFound(group != null);
        if (group != null) {
            group.forEach((key, count) -> reply.addPairs(
                    Pair.newBuilder().setKey(key).setValue(count)));
        }
        out.onNext(reply.build());
        out.onCompleted();
    }

    /**
     * A channel to a peer, reused across reads.
     *
     * <p>ADOPTION EDIT. A simulated node has no sockets, so the body
     * below has to become {@code return dissaly.api.Dissaly.current().channelTo(address);}
     * and the {@code channels} field and its imports go with it. Left as it is,
     * the first read fails with "No functional channel service provider found"
     * and the run ends having done no work. TRANSFORMATION.md has the line.
     */
    protected final Channel channel(String address) {
        return channels.computeIfAbsent(address,
                a -> io.grpc.ManagedChannelBuilder.forTarget(a).usePlaintext().build());
    }
}
